name: Gradle Wrapper Command

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"  # Specify the version of JDK you want

      - name: Run Gradle Wrapper
        run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi

          # Set permissions for the wrapper script
          chmod +x gradlew
          # Check for Gradle build files, and initialize if none exist
          if [ ! -f "build.gradle" ] && [ ! -f "settings.gradle" ]; then
            echo "No Gradle build files found. Initializing Gradle project..."
            ./gradlew init
          fi

          # Now run Gradle command
          ./gradlew --version  # Replace this with a specific Gradle task if needed
          

